apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: janinix/ambulance-ufe
  newName: janinix/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260316.1048 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: janinix/ambulance-wl-webapi
  newName: janinix/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260330.0956 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
