apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xmarecek-ambulance-wl
    wac-fiit.github.io/project: xmarecek-ambulance-wl 
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/xmarecek-ambulance-ufe
- ../../../apps/xmarecek-ambulance-webapi


components:
- ../../../components/version-release